services:
    splunk:
        image: "splunk/splunk:${SPLUNK_VERSION}"
        container_name: splunk
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_PASSWORD=changed!
            - SPLUNK_APPS_URL=https://github.com/splunk/sdk-app-collection/releases/download/v1.1.0/sdkappcollection.tgz
        ports:
            - "8000:8000"
            - "8088:8088"
            - "8089:8089"
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000']
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
            - "./tests/system/test_apps/eventing_app:/opt/splunk/etc/apps/eventing_app"
            - "./tests/system/test_apps/generating_app:/opt/splunk/etc/apps/generating_app"
            - "./tests/system/test_apps/reporting_app:/opt/splunk/etc/apps/reporting_app"
            - "./tests/system/test_apps/streaming_app:/opt/splunk/etc/apps/streaming_app"
            - "./tests/system/test_apps/modularinput_app:/opt/splunk/etc/apps/modularinput_app"
            - "./splunklib:/opt/splunk/etc/apps/eventing_app/lib/splunklib"
            - "./splunklib:/opt/splunk/etc/apps/generating_app/lib/splunklib"
            - "./splunklib:/opt/splunk/etc/apps/reporting_app/lib/splunklib"
            - "./splunklib:/opt/splunk/etc/apps/streaming_app/lib/splunklib"
            - "./splunklib:/opt/splunk/etc/apps/modularinput_app/lib/splunklib"
